# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "8:00"
      timezone: "America/Denver"
    target-branch: "develop"
    labels:
      - "dependencies"
      - "global"
    reviewers:
      - "Thenlie"
    assignees:
      - "dependabot"

  - package-ecosystem: "npm"
    directory: "/packages/rgbee" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "8:00"
      timezone: "America/Denver"
    target-branch: "develop"
    labels:
      - "dependencies"
      - "rgbee"
    reviewers:
      - "Thenlie"
    assignees:
      - "dependabot"

  - package-ecosystem: "npm"
    directory: "/packages/pages" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "8:00"
      timezone: "America/Denver"
    target-branch: "develop"
    labels:
      - "dependencies"
      - "pages"
    reviewers:
      - "Thenlie"
    assignees:
      - "dependabot"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "10:00"
      timezone: "America/Denver"
    target-branch: "develop"
    labels:
      - "dependencies"
    reviewers:
      - "Thenlie"
    assignees:
      - "dependabot"
